server {
  listen 80;
  server_name localhost;
  client_max_body_size 5G;
  access_log /var/log/nginx/host.access.log main;
  error_log /var/log/nginx/error.log error;
  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }
  location /api/ {
    rewrite /api/(.*) /$1 break;
    proxy_pass http://192.168.109.198:8080;
  }
  location /pyanalysis/ {
    rewrite /pyanalysis/(.*) /$1 break;
    proxy_pass http://192.168.109.198:8086;
  }
  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /usr/share/nginx/html;
  }
}